apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager-service
spec:
  selector:
    alertmanager: alertmanager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: web
      name: http
    - protocol: TCP
      port: 8081
      targetPort: reloader-web
      name: http-reloader
