apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      path: /alertmanager/metrics
      port: http
    - interval: 30s
      path: /metrics
      port: http-reloader
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager-service
