apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-v1
  namespace: api
  labels:
    app.kubernetes.io/name: products
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: products
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: products
        app.kubernetes.io/version: v1
    spec:
      imagePullSecrets:
        - name: nexus-docker-public
      containers:
        - name: products
          image: nexus.sogeor.com/docker-public/sogeor/products-service:master
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server.api.svc.cluster.local:8080"
            - name: MONGODB_HOST
              value: "mongodb-cluster-mongos"
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: products-mongodb-cluster-user
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-mongodb-cluster-user
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "http://kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KC_ISSUER_URI
              value: "https://sso.sogeor.com/realms/system"
            - name: KC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: products
                  key: client-id
            - name: KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: products
                  key: client-secret
          ports:
            - name: http
              containerPort: 8080
            - name: http-management
              containerPort: 9090
          startupProbe:
            httpGet:
              path: /v1/products/actuator/health
              port: http-management
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /v1/products/actuator/health
              port: http-management
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /v1/products/actuator/health
              port: http-management
            periodSeconds: 30
            failureThreshold: 6
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
