apiVersion: v1
kind: Service
metadata:
  name: mongodb-cluster-exporter
  namespace: api
  labels:
    app.kubernetes.io/name: mongodb-cluster-exporter-service
spec:
  selector:
    app.kubernetes.io/name: mongodb-cluster-exporter
  ports:
    - protocol: TCP
      port: 9216
      targetPort: metrics
      name: metrics
  type: ClusterIP
