apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: api
  labels:
    app.kubernetes.io/name: config-server-service
spec:
  selector:
    app.kubernetes.io/name: config-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      name: http
    - protocol: TCP
      port: 9090
      targetPort: http-management
      name: http-management
  type: ClusterIP
