apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-v1
  namespace: api
  labels:
    app.kubernetes.io/name: payments
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payments
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payments
        app.kubernetes.io/version: v1
    spec:
      imagePullSecrets:
        - name: nexus-docker-public
      containers:
        - name: payments
          image: nexus.sogeor.com/docker-public/sogeor/payments-service:master
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server.api.svc.cluster.local:8080"
            - name: R2DBC_URL
              value: "r2dbc:postgresql://postgres-cluster-pooler-rw:5432/payments"
            - name: R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payments-postgres-cluster-role
                  key: username
            - name: R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payments-postgres-cluster-role
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "http://kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KC_ISSUER_URI
              value: "https://sso.sogeor.com/realms/system"
            - name: KC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: payments
                  key: client-id
            - name: KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments
                  key: client-secret
          ports:
            - name: http
              containerPort: 8080
            - name: http-management
              containerPort: 9090
          startupProbe:
            httpGet:
              path: /v1/payments/actuator/health
              port: http-management
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /v1/payments/actuator/health
              port: http-management
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /v1/payments/actuator/health
              port: http-management
            periodSeconds: 30
            failureThreshold: 6
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
