apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: service
spec:
  endpoints:
    - interval: 15s
      path: /grafana/metrics
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-service
