apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-service
spec:
  selector:
    prometheus: prometheus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: web
      name: http
    - protocol: TCP
      port: 8081
      targetPort: reloader-web
      name: http-reloader
  sessionAffinity: ClientIP
